enum LanguageCode {
	Arabic = "ar",
	Bulgarian = "bg",
	Catalan = "ca",
	Czech = "cs",
	Danish = "da",
	Dutch = "nl",
	English = "en",
	Finnish = "fi",
	French = "fr",
	German = "de",
	Greek = "el",
	Hebrew = "he",
	Hindi = "hi",
	Hungarian = "hu",
	Indonesian = "id",
	Italian = "it",
	Japanese = "ja",
	Korean = "ko",
	Latvian = "lv",
	Lithuanian = "lt",
	Norwegian = "no",
	Polish = "pl",
	Portuguese = "pt",
	Romanian = "ro",
	Russian = "ru",
	Slovak = "sk",
	Slovenian = "sl",
	Spanish = "es",
	Swedish = "sv",
	Thai = "th",
	Turkish = "tr",
	Ukrainian = "uk",
	Vietnamese = "vi",
	Chinese = "zh",
}

export { LanguageCode };
